### ISSUE TITLE
Add ability to forward authorization from ESI to recruiters to avoid duplicate "SSOing"?

### ISSUE THREAD

**Issue by NyxVxyN** [ddouglas/esiknife#14]
Feature request.

If the characters have already auth'd on ESI with SSO, surely there is a way that can avoid them having to SSO all their characters twice when giving to s recruiter, this is incredibly long winded, putting a lot of people off.

**Comment by ddavaham** [comment]
Not saying this isn't an issue, and I will be working on adding the ability to authorize multiple chars on a single grant this weekend, BUT in the meantime follow the process below.

1) Authenticate all character as alts.
2) Click on the link on char, authorize the grant
3) Use the Alt Hotswap accessible from the User Dropdown menu in the top right to switch to other characters.
4) After switch to another character, click on the link again.
5) Repeat Steps 1- 5 for all chars.
