### ISSUE TITLE
[Feature Request] Refresh Information

### ISSUE THREAD

**Issue by evemarco** [ddouglas/esiknife#15]
Is there a way to have the information refreshed at regular intervals, like every 24 hours, for example? I do not see an update over time, once authentication and scopes validated. Thx.

**Comment by ddavaham** [comment]
Already in the works. Was working on it last weekend. Anticipating a
release early next week with this and a couple other features.

**Comment by ddavaham** [comment]
So RL got in the way. I apologize. This feature is still in the pipeline, but I cannot promise when it will be done. soon(tm) :-D

**Comment by ddouglas** [comment]
This feature never actually got completed. I apologize for this. I'm working on a new iteration of this application that will have this built in. Please follow https://github.com/eveisesi/athena for updates
