### ISSUE TITLE
HTTP 500 when viewing another character

### ISSUE THREAD

**Issue by MartinLockheart** [ddouglas/esiknife#16]
Hello! I had someone give me access to their character on ESI Knife today, but when I click to view their character, I'm going to an error page. 

beta.esiknife.space is currently unable to handle this request.
HTTP ERROR 500

I've tried it periodically over the past few hours, but no luck.

**Comment by ddavaham** [comment]
This is due to the character not having selected any scopes when they initially authenticated. Please tell the character to go to the settings page and delete their account and then log back in again, this time selecting all the scopes.
