### ISSUE TITLE
Error 526 - Invalid SSL Certificate on https://status.esiknife.space/

### ISSUE THREAD

**Issue by BlubQ** [ddouglas/esiknife#21]
The following website returns a "526 - Invalid SSL Certificate" error:
https://status.esiknife.space/
![image](https://user-images.githubusercontent.com/30180530/81620872-2b3a6180-93ed-11ea-8c22-d55668bf5987.png)

The reason I noticed is because it is linked on zkillboard when there seems to be an issue with the API.
<img width="1322" alt="chrome_J8eb1SqS9e" src="https://user-images.githubusercontent.com/30180530/81620883-32616f80-93ed-11ea-95e1-a8d5e2eff1ed.png">

**Comment by ddouglas** [comment]
Oh god I forgot he did that.

**Comment by ddouglas** [comment]
Okay this is back and running. Ty
