### ISSUE TITLE
Authorization to View

### ISSUE THREAD

**Issue by Stickumnote** [ddouglas/esiknife#7]
i currently lost my authorization to view the shared ESI's I have for my corp mates. do you have any solutions for this? i can't view any of them sine a few weeks ago.

**Comment by Stickumnote** [comment]
also they are in the list of "authorized to view" Char.

**Comment by Stickumnote** [comment]
https://gyazo.com/d333a67c23204916990d7b10b09fa562

**Comment by ddavaham** [comment]
Sorry about that. Forgot that the overview doesn't have a scope associated with it. I guess I only tested this when an alt and not a accessee. My apologies. Should be all good now
